steps:
- id: 'Go Build'
  name: golang
  args: ['go', 'build', '.', '-o', 'web-greeting']

artifacts:
  objects:
    location: gs://bu-gcpdevops-labs-eusw
    paths: ["./web-greeting"]

options:
  logging: CLOUD_LOGGING_ONLY